<a href="https://colab.research.google.com/github/nadeemkhanrtm1/video-game-analysis/blob/main/video_game_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Video Game Analysis

In [172]:
import numpy as np;
import pandas as pd;
from sklearn.impute import SimpleImputer;

In [176]:
data = pd.read_csv("video-game-analysis.csv")

In [151]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  object
 1   title         64016 non-null  object
 2   console       64016 non-null  object
 3   genre         64016 non-null  object
 4   publisher     64016 non-null  object
 5   developer     63999 non-null  object
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object
 13  last_update   17879 non-null  object
dtypes: float64(6), object(8)
memory usage: 6.8+ MB

In [153]:
data.shape

(64016, 14)

In [181]:
data = data.drop(columns=["img"])

In [156]:
data.shape

(64016, 13)

In [157]:
data.isna().sum()

title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64

In [158]:
data.convert_dtypes()

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,<NA>
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.6,9.71,3.02,2014-11-18,2018-01-03
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,<NA>
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,<NA>,15.86,9.06,0.06,5.33,1.42,2013-09-17,<NA>
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2016-08-11,2019-01-28
64012,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2020-07-30,2020-05-09
64013,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2020-07-30,2020-05-09
64014,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2019-02-28,2019-02-24
64015,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023-09-29

In [159]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         64016 non-null  object
 1   console       64016 non-null  object
 2   genre         64016 non-null  object
 3   publisher     64016 non-null  object
 4   developer     63999 non-null  object
 5   critic_score  6678 non-null   float64
 6   total_sales   18922 non-null  float64
 7   na_sales      12637 non-null  float64
 8   jp_sales      6726 non-null   float64
 9   pal_sales     12824 non-null  float64
 10  other_sales   15128 non-null  float64
 11  release_date  56965 non-null  object
 12  last_update   17879 non-null  object
dtypes: float64(6), object(7)
memory usage: 6.3+ MB

In [177]:
data = data.convert_dtypes()

In [162]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         64016 non-null  string
 1   console       64016 non-null  string
 2   genre         64016 non-null  string
 3   publisher     64016 non-null  string
 4   developer     63999 non-null  string
 5   critic_score  6678 non-null   Float64
 6   total_sales   18922 non-null  Float64
 7   na_sales      12637 non-null  Float64
 8   jp_sales      6726 non-null   Float64
 9   pal_sales     12824 non-null  Float64
 10  other_sales   15128 non-null  Float64
 11  release_date  56965 non-null  string
 12  last_update   17879 non-null  string
dtypes: Float64(6), string(7)
memory usage: 6.7 MB

In [163]:
data.isna().sum()

title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64

In [164]:
data.select_dtypes("number")

       critic_score  total_sales  na_sales  jp_sales  pal_sales  other_sales
0               9.4        20.32      6.37      0.99       9.85         3.12
1               9.7        19.39      6.06       0.6       9.71         3.02
2               9.6        16.15      8.41      0.47       5.49         1.78
3              <NA>        15.86      9.06      0.06       5.33         1.42
4               8.1        15.09      6.18      0.41       6.05         2.44
...             ...          ...       ...       ...        ...          ...
64011          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>
64012          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>
64013          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>
64014          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>
64015          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>

[64016 rows x 6 columns]

In [165]:
data.select_dtypes(include=np.number)

       critic_score  total_sales  na_sales  jp_sales  pal_sales  other_sales
0               9.4        20.32      6.37      0.99       9.85         3.12
1               9.7        19.39      6.06       0.6       9.71         3.02
2               9.6        16.15      8.41      0.47       5.49         1.78
3              <NA>        15.86      9.06      0.06       5.33         1.42
4               8.1        15.09      6.18      0.41       6.05         2.44
...             ...          ...       ...       ...        ...          ...
64011          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>
64012          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>
64013          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>
64014          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>
64015          <NA>         <NA>      <NA>      <NA>       <NA>         <NA>

[64016 rows x 6 columns]

In [179]:
nums_cols = data.select_dtypes('number').columns.tolist()

In [183]:
imputer = SimpleImputer(strategy='mean')

In [184]:
imputer.fit(data[nums_cols])

## data[nums_cols] = imputer.fit_transform(data[nums_cols])

SimpleImputer()

In [182]:
data.head()

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,<NA>
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.6,9.71,3.02,2014-11-18,2018-01-03
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,<NA>
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,<NA>,15.86,9.06,0.06,5.33,1.42,2013-09-17,<NA>
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14