<a href="https://colab.research.google.com/github/nadeemkhanrtm1/video-game-analysis/blob/main/video_game_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/021/299/original/final_vg.csv

--2026-05-03 00:30:03--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/021/299/original/final_vg.csv
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 18.64.229.71, 18.64.229.135, 18.64.229.172, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|18.64.229.71|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2026-05-03 00:30:03 ERROR 403: Forbidden.

In [67]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/021/299/original/final_vg1_-_final_vg_%281%29.csv

--2026-05-03 01:37:44--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/021/299/original/final_vg1_-_final_vg_%281%29.csv
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 18.64.229.71, 18.64.229.135, 18.64.229.172, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|18.64.229.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2041483 (1.9M) [text/plain]
Saving to: ‘final_vg1_-_final_vg_(1).csv.2’

final_vg1_-_final_v 100%[===================>]   1.95M  --.-KB/s    in 0.06s

2026-05-03 01:37:44 (31.2 MB/s) - ‘final_vg1_-_final_vg_(1).csv.2’ saved [2041483/2041483]

In [68]:
import pandas as pd;
import numpy as np;
data = pd.read_csv("final_vg1_-_final_vg_(1).csv")
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,2061,1942,NES,1985.0,Shooter,Capcom,4.569217,3.033887,3.439352,1.991671,12.802935
1,9137,¡Shin Chan Flipa en colores!,DS,2007.0,Platform,505 Games,2.076955,1.493442,3.033887,0.394830,7.034163
2,14279,.hack: Sekai no Mukou ni + Versus,PS3,2012.0,Action,Namco Bandai Games,1.145709,1.762339,1.493442,0.408693,4.982552
3,8359,.hack//G.U. Vol.1//Rebirth,PS2,2006.0,Role-Playing,Namco Bandai Games,2.031986,1.389856,3.228043,0.394830,7.226880
4,7109,.hack//G.U. Vol.2//Reminisce,PS2,2006.0,Role-Playing,Namco Bandai Games,2.792725,2.592054,1.440483,1.493442,8.363113

In [ ]:
## To fnd what kind of games they should start creating to get higher success in the market

In [ ]:
## what kind of games do they have today ?

In [ ]:
data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,2061,1942,NES,1985.0,Shooter,Capcom,4.569217,3.033887,3.439352,1.991671,12.802935
1,9137,¡Shin Chan Flipa en colores!,DS,2007.0,Platform,505 Games,2.076955,1.493442,3.033887,0.394830,7.034163
2,14279,.hack: Sekai no Mukou ni + Versus,PS3,2012.0,Action,Namco Bandai Games,1.145709,1.762339,1.493442,0.408693,4.982552
3,8359,.hack//G.U. Vol.1//Rebirth,PS2,2006.0,Role-Playing,Namco Bandai Games,2.031986,1.389856,3.228043,0.394830,7.226880
4,7109,.hack//G.U. Vol.2//Reminisce,PS2,2006.0,Role-Playing,Namco Bandai Games,2.792725,2.592054,1.440483,1.493442,8.363113
...,...,...,...,...,...,...,...,...,...,...,...
16647,7925,Zumba Fitness Rush,X360,2012.0,Sports,505 Games,4.409308,3.167419,4.168474,1.087977,13.053204
16648,6279,Zumba Fitness: World Party,Wii,2013.0,Misc,Majesco Entertainment,3.033887,2.792725,1.596852,1.493442,8.878837
16649,6977,Zumba Fitness: World Party,XOne,2013.0,Misc,Majesco Entertainment,3.228043,2.004268,1.833151,1.087977,7.954274
16650,15422,Zwei!!,PSP,2008.0,Role-Playing,Falcom Corporation,1.087977,0.592445,1.087977,0.394830,3.509168
16651,12919,Zyuden Sentai Kyoryuger: Game de Gaburincho!!,3DS,2013.0,Action,Namco Bandai Games,1.081046,1.714664,2.004268,0.394830,5.132196

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16652 entries, 0 to 16651
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16652 non-null  int64
 1   Name          16652 non-null  object
 2   Platform      16652 non-null  object
 3   Year          16381 non-null  float64
 4   Genre         16652 non-null  object
 5   Publisher     16594 non-null  object
 6   NA_Sales      16652 non-null  float64
 7   EU_Sales      16652 non-null  float64
 8   JP_Sales      16652 non-null  float64
 9   Other_Sales   16652 non-null  float64
 10  Global_Sales  16652 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [ ]:
data["Genre"].unique()

array(['Shooter', 'Platform', 'Action', 'Role-Playing', 'Racing', 'Misc',
       'Adventure', 'Sports', 'Puzzle', 'Simulation', 'Strategy',
       'Fighting'], dtype=object)

In [ ]:
type_of_games = data["Genre"].unique()

In [ ]:
type_of_games

array(['Shooter', 'Platform', 'Action', 'Role-Playing', 'Racing', 'Misc',
       'Adventure', 'Sports', 'Puzzle', 'Simulation', 'Strategy',
       'Fighting'], dtype=object)

In [ ]:
len(type_of_games)

12

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16652 entries, 0 to 16651
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16652 non-null  int64
 1   Name          16652 non-null  object
 2   Platform      16652 non-null  object
 3   Year          16381 non-null  float64
 4   Genre         16652 non-null  object
 5   Publisher     16594 non-null  object
 6   NA_Sales      16652 non-null  float64
 7   EU_Sales      16652 non-null  float64
 8   JP_Sales      16652 non-null  float64
 9   Other_Sales   16652 non-null  float64
 10  Global_Sales  16652 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [ ]:
data.head(50)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,2061,1942,NES,1985.0,Shooter,Capcom,4.569217,3.033887,3.439352,1.991671,12.802935
1,9137,¡Shin Chan Flipa en colores!,DS,2007.0,Platform,505 Games,2.076955,1.493442,3.033887,0.394830,7.034163
2,14279,.hack: Sekai no Mukou ni + Versus,PS3,2012.0,Action,Namco Bandai Games,1.145709,1.762339,1.493442,0.408693,4.982552
3,8359,.hack//G.U. Vol.1//Rebirth,PS2,2006.0,Role-Playing,Namco Bandai Games,2.031986,1.389856,3.228043,0.394830,7.226880
4,7109,.hack//G.U. Vol.2//Reminisce,PS2,2006.0,Role-Playing,Namco Bandai Games,2.792725,2.592054,1.440483,1.493442,8.363113
5,8604,.hack//G.U. Vol.2//Reminisce (jp sales),PS2,2006.0,Role-Playing,Namco Bandai Games,2.456509,1.435228,3.167419,0.471076,7.536614
6,8306,.hack//G.U. Vol.3//Redemption,PS2,2007.0,Role-Playing,Namco Bandai Games,2.031986,1.389856,3.228043,0.394830,7.226880
7,1565,.hack//Infection Part 1,PS2,2002.0,Role-Playing,Atari,4.286650,4.032416,3.652926,2.959779,14.931772
8,9076,.hack//Link,PSP,2010.0,Role-Playing,Namco Bandai Games,2.076955,1.493442,3.033887,0.394830,7.034163
9,3004,.hack//Mutation Part 2,PS2,2002.0,Role-Playing,Atari,3.530324,3.285202,3.390562,2.186589,12.392677
10,4296,.hack//Outbreak Part 3,PS2,2002.0,Role-Playing,Atari,3.033887,2.792725,3.228043,1.781124,10.835780
11,8009,.hack//Quarantine Part 4: The Final Chapter,PS2,2003.0,Role-Playing,Atari,2.592054,2.340740,2.302032,1.087977,8.456194
12,2576,[Prototype 2],X360,2012.0,Action,Activision,4.266031,3.613706,3.054533,2.340740,13.127289
13,2742,[Prototype 2],PS3,2012.0,Action,Activision,3.978349,3.727034,0.848807,2.792725,11.447989
14,10598,[Prototype 2],PC,2012.0,Action,Activision,2.340740,1.087977,3.289261,0.394830,7.368439
15,1505,[Prototype],X360,2009.0,Action,Activision,4.825647,3.950178,1.168471,2.879736,12.764975
16,1604,[Prototype],PS3,2009.0,Action,Activision,4.569217,4.108402,1.187272,3.339269,13.181205
17,3770,007 Racing,PS,2000.0,Racing,Electronic Arts,3.796027,3.390562,4.099309,1.493442,13.150085
18,1275,007: Quantum of Solace,X360,2008.0,Action,Activision,4.801549,4.346074,0.394830,3.033887,12.576340
19,1741,007: Quantum of Solace,PS3,2008.0,Action,Activision,4.156030,4.346074,1.087977,3.390562,12.980643
20,3040,007: Quantum of Solace,Wii,2008.0,Action,Activision,3.796027,3.762126,0.394830,2.340740,10.293723
21,4501,007: Quantum of Solace,PS2,2008.0,Action,Activision,3.228043,2.738800,2.585598,3.652926,11.780257
22,9320,007: Quantum of Solace,DS,2008.0,Action,Activision,2.792725,0.394830,2.854554,0.394830,6.529231
23,14550,007: Quantum of Solace,PC,2008.0,Action,Activision,0.394830,0.394830,2.207480,0.422556,3.663461
24,1202,007: The World is not Enough,N64,2000.0,Action,Electronic Arts,5.122218,4.032416,1.087977,1.493442,11.736053
25,2249,007: The World is not Enough,PS,2000.0,Action,Electronic Arts,4.326655,3.950178,3.340462,2.186589,14.069816
26,421,007: Tomorrow Never Dies,PS,1999.0,Shooter,Electronic Arts,5.542324,5.285179,2.024665,3.167419,16.048985
27,11233,1 vs. 100,DS,2008.0,Misc,DSI Games,2.474271,1.473283,3.070446,0.394830,7.419877
28,16115,1/2 Summer +,PSP,2013.0,Adventure,Kaga Create,1.493442,0.394830,0.394830,0.394830,3.046999
29,11414,10 Minute Solution,Wii,2010.0,Sports,Activision,2.186589,0.394830,2.350446,0.394830,5.453810
30,3888,100 All-Time Favorites,DS,2009.0,Puzzle,Ubisoft,3.950178,2.879736,3.792857,1.781124,12.028298
31,3008,100 Classic Books,DS,2008.0,Misc,Nintendo,2.959779,4.346074,2.075807,1.087977,11.114977
32,13892,100 Classic Games,DS,2011.0,Misc,Rondomedia,2.176522,1.493442,2.702014,0.443350,6.856285
33,14635,1000 Cooking Recipes from ELLE à table,DS,2010.0,Misc,Nintendo,2.437787,1.087977,2.088056,0.579103,5.961887
34,5538,1001 Touch Games,DS,2011.0,Action,Avanquest,2.879736,3.228043,1.111199,1.781124,8.880024
35,7712,101-in-1 Explosive Megamix,DS,2008.0,Puzzle,Nordcurrent,2.004268,2.959779,2.190798,1.087977,8.075912
36,7115,101-in-1 Party Megamix Wii,Wii,2009.0,Misc,Nordcurrent,3.339269,0.394830,3.748889,1.087977,8.885592
37,11310,101-in-1 Sports Megamix,DS,2010.0,Sports,Nordcurrent,2.474271,1.473283,3.070446,0.394830,7.419877
38,14623,101-in-1 Sports Party Megamix,Wii,2010.0,Sports,Nordcurrent,1.087977,1.246108,3.333188,0.394830,6.124095
39,839,1080°: TenEighty Snowboarding,N64,1998.0,Sports,Nintendo,5.223144,4.505704,2.959779,2.004268,14.692894
40,15008,11eyes: CrossOver,X360,2009.0,Adventure,5pb,1.087977,0.592445,1.087977,0.394830,3.509168
41,15555,11eyes: CrossOver,PSP,2010.0,Adventure,5pb,1.087977,0.592445,1.087977,0.394830,3.509168
42,12237,12-Sai. Honto no Kimochi,3DS,2014.0,Adventure,Happinet,1.892812,0.394830,2.340740,0.443350,5.284352
43,14007,12-Sai. Koisuru Diary,3DS,2016.0,Adventure,Happinet,1.493442,0.394830,1.781124,0.394830,4.085704
44,13692,12Riven: The Psi-Climinal of Integral,PS2,2008.0,Adventure,CyberFront,1.493442,0.394830,1.781124,0.394830,4.085704
45,16543,15 Days,PC,2009.0,Adventure,DTP Entertainment,1.892812,0.394830,2.340740,0.443350,5.284352
46,5843,1701 A.D.,PC,2006.0,Simulation,Deep Silver,3.529232,3.613706,2.887151,2.004268,12.061883
47,4832,18 Wheeler: American Pro Trucker,PS2,2001.0,Racing,Acclaim Entertainment,3.390562,3.102880,3.320183,2.004268,12.017428
48,10077,18 Wheeler: American Pro Trucker,GC,2002.0,Racing,Acclaim Entertainment,2.592054,1.087977,3.820301,1.450116,9.376658
49,15155,18 Wheels of Steel: Extreme Trucker,PC,2009.0,Racing,Rondomedia,2.437787,1.087977,2.088056,0.579103,5.961887

In [20]:
data[data["Rank"] <= 10]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
3722,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,8.293241,4.537965,3.727034,4.244977,20.803217
7895,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,7.763170,7.555676,6.332366,6.196948,27.848159
9609,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,7.431857,7.222459,6.871802,6.064711,27.590829
9612,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,7.680336,6.954445,6.547563,5.815365,26.997709
10583,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,7.422144,7.184927,7.324347,5.000000,26.931418
13448,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,8.370051,6.275363,6.918392,4.738635,26.302441
13923,6,Tetris,GB,1989.0,Puzzle,Nintendo,8.144152,5.815365,6.439835,4.455273,24.854625
15932,8,Wii Play,Wii,2006.0,Misc,Nintendo,7.641198,7.219203,6.075002,6.047319,26.982723
15934,1,Wii Sports,Wii,2006.0,Sports,Nintendo,8.725452,8.367985,6.327075,7.135349,30.555862
15936,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,7.756840,7.398804,6.187843,6.085189,27.428677

In [17]:
data['Global_Sales'].max()

30.55586186

In [21]:
data[data["Rank"] <= 10].sort_values(by='Rank')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
15934,1,Wii Sports,Wii,2006.0,Sports,Nintendo,8.725452,8.367985,6.327075,7.135349,30.555862
13448,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,8.370051,6.275363,6.918392,4.738635,26.302441
7895,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,7.763170,7.555676,6.332366,6.196948,27.848159
15936,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,7.756840,7.398804,6.187843,6.085189,27.428677
10583,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,7.422144,7.184927,7.324347,5.000000,26.931418
13923,6,Tetris,GB,1989.0,Puzzle,Nintendo,8.144152,5.815365,6.439835,4.455273,24.854625
9609,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,7.431857,7.222459,6.871802,6.064711,27.590829
15932,8,Wii Play,Wii,2006.0,Misc,Nintendo,7.641198,7.219203,6.075002,6.047319,26.982723
9612,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,7.680336,6.954445,6.547563,5.815365,26.997709
3722,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,8.293241,4.537965,3.727034,4.244977,20.803217

In [22]:
#platform - specific hardware, OS where game played
#Year - which year game being launched
#Genre - Category of game
#Publisher - Game Company Name
#NA_Sales - North America Sales
#EU_Sales - Europe Sales
#JP_Sales - Japan Sales
#Other_Sales - Other Sales
#Global_Sales - Global Sales

In [23]:
# How many year of data has been provided to us and prediction to what year ?

In [31]:
data['Year'].unique()

array([1985., 2007., 2012., 2006., 2002., 2010., 2003., 2009., 2000.,
       2008., 1999., 2013., 2011., 1998., 2014., 2016., 2001., 2005.,
       2004., 1996., 1995., 2015., 1984., 1997., 1994., 1982.,   nan,
       1986., 1989., 1981., 1980., 1983., 1992., 2017., 2019., 1991.,
       1993., 1987., 1990., 1988., 2018., 2020.])

In [37]:
data['Year'].astype(dtype="int64")

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16652 entries, 0 to 16651
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16652 non-null  int64
 1   Name          16652 non-null  object
 2   Platform      16652 non-null  object
 3   Year          16381 non-null  float64
 4   Genre         16652 non-null  object
 5   Publisher     16594 non-null  object
 6   NA_Sales      16652 non-null  float64
 7   EU_Sales      16652 non-null  float64
 8   JP_Sales      16652 non-null  float64
 9   Other_Sales   16652 non-null  float64
 10  Global_Sales  16652 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [44]:
data[data['Year'].isna()]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
174,11078,Action Man-Operation Extreme,PS,NaN,Action,NaN,2.004268,1.493442,3.148945,0.394830,7.171562
190,3219,Advance Wars: Days of Ruin,DS,NaN,Strategy,Nintendo,4.179019,2.959779,3.739266,2.186589,12.704753
193,1515,Adventure,2600,NaN,Adventure,Atari,5.190620,2.474271,4.964656,0.394830,13.815070
226,16249,Agarest Senki: Re-appearance,PS3,NaN,Role-Playing,Idea Factory,1.493442,0.394830,0.394830,0.394830,3.046999
266,2115,Air-Sea Battle,2600,NaN,Shooter,Atari,4.905689,2.186589,4.622424,0.394830,13.238565
...,...,...,...,...,...,...,...,...,...,...,...
16415,2136,Yakuza 4,PS3,NaN,Action,Sega,3.102880,3.033887,4.537965,2.004268,12.678999
16454,12137,Yoostar on MTV,X360,NaN,Misc,Unknown,2.186589,0.929210,2.044206,0.595842,5.790349
16499,7353,Yu Yu Hakusho: Dark Tournament,PS2,NaN,Fighting,NaN,2.697415,2.474271,2.520105,1.493442,9.257057
16507,15479,Yu-Gi-Oh! 5D's Wheelie Breakers (JP sales),Wii,NaN,Racing,Unknown,1.087977,0.592445,1.087977,0.394830,3.509168
16590,11411,Zero: Tsukihami no Kamen,Wii,NaN,Action,Nintendo,0.415624,0.394830,2.474271,0.505733,3.746329

In [45]:
data[data['Year'].isnull()]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
174,11078,Action Man-Operation Extreme,PS,NaN,Action,NaN,2.004268,1.493442,3.148945,0.394830,7.171562
190,3219,Advance Wars: Days of Ruin,DS,NaN,Strategy,Nintendo,4.179019,2.959779,3.739266,2.186589,12.704753
193,1515,Adventure,2600,NaN,Adventure,Atari,5.190620,2.474271,4.964656,0.394830,13.815070
226,16249,Agarest Senki: Re-appearance,PS3,NaN,Role-Playing,Idea Factory,1.493442,0.394830,0.394830,0.394830,3.046999
266,2115,Air-Sea Battle,2600,NaN,Shooter,Atari,4.905689,2.186589,4.622424,0.394830,13.238565
...,...,...,...,...,...,...,...,...,...,...,...
16415,2136,Yakuza 4,PS3,NaN,Action,Sega,3.102880,3.033887,4.537965,2.004268,12.678999
16454,12137,Yoostar on MTV,X360,NaN,Misc,Unknown,2.186589,0.929210,2.044206,0.595842,5.790349
16499,7353,Yu Yu Hakusho: Dark Tournament,PS2,NaN,Fighting,NaN,2.697415,2.474271,2.520105,1.493442,9.257057
16507,15479,Yu-Gi-Oh! 5D's Wheelie Breakers (JP sales),Wii,NaN,Racing,Unknown,1.087977,0.592445,1.087977,0.394830,3.509168
16590,11411,Zero: Tsukihami no Kamen,Wii,NaN,Action,Nintendo,0.415624,0.394830,2.474271,0.505733,3.746329

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16652 entries, 0 to 16651
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16652 non-null  int64
 1   Name          16652 non-null  object
 2   Platform      16652 non-null  object
 3   Year          16381 non-null  float64
 4   Genre         16652 non-null  object
 5   Publisher     16594 non-null  object
 6   NA_Sales      16652 non-null  float64
 7   EU_Sales      16652 non-null  float64
 8   JP_Sales      16652 non-null  float64
 9   Other_Sales   16652 non-null  float64
 10  Global_Sales  16652 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [47]:
len(data)

16652

In [48]:
data.Year.isna().sum()

np.int64(271)

In [51]:
data['Year'].isna().sum()   # Should output 271

np.int64(271)

In [52]:
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,2061,1942,NES,1985.0,Shooter,Capcom,4.569217,3.033887,3.439352,1.991671,12.802935
1,9137,¡Shin Chan Flipa en colores!,DS,2007.0,Platform,505 Games,2.076955,1.493442,3.033887,0.394830,7.034163
2,14279,.hack: Sekai no Mukou ni + Versus,PS3,2012.0,Action,Namco Bandai Games,1.145709,1.762339,1.493442,0.408693,4.982552
3,8359,.hack//G.U. Vol.1//Rebirth,PS2,2006.0,Role-Playing,Namco Bandai Games,2.031986,1.389856,3.228043,0.394830,7.226880
4,7109,.hack//G.U. Vol.2//Reminisce,PS2,2006.0,Role-Playing,Namco Bandai Games,2.792725,2.592054,1.440483,1.493442,8.363113

In [54]:
data['Year'].mode

<bound method Series.mode of 0        1985.0
1        2007.0
2        2012.0
3        2006.0
4        2006.0
          ...
16647    2012.0
16648    2013.0
16649    2013.0
16650    2008.0
16651    2013.0
Name: Year, Length: 16652, dtype: float64>

In [55]:
data['Year'].mean()

np.float64(2006.3905133996705)

In [62]:
pd.to_numeric(data['Year'], errors="coerce").astype("Int64")

0        1985
1        2007
2        2012
3        2006
4        2006
         ...
16647    2012
16648    2013
16649    2013
16650    2008
16651    2013
Name: Year, Length: 16652, dtype: Int64

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16652 entries, 0 to 16651
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16652 non-null  int64
 1   Name          16652 non-null  object
 2   Platform      16652 non-null  object
 3   Year          16381 non-null  float64
 4   Genre         16652 non-null  object
 5   Publisher     16594 non-null  object
 6   NA_Sales      16652 non-null  float64
 7   EU_Sales      16652 non-null  float64
 8   JP_Sales      16652 non-null  float64
 9   Other_Sales   16652 non-null  float64
 10  Global_Sales  16652 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [65]:
data['Year'] = pd.to_numeric(data['Year'].notna(), errors="coerce").astype(int)

In [66]:
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,2061,1942,NES,1,Shooter,Capcom,4.569217,3.033887,3.439352,1.991671,12.802935
1,9137,¡Shin Chan Flipa en colores!,DS,1,Platform,505 Games,2.076955,1.493442,3.033887,0.394830,7.034163
2,14279,.hack: Sekai no Mukou ni + Versus,PS3,1,Action,Namco Bandai Games,1.145709,1.762339,1.493442,0.408693,4.982552
3,8359,.hack//G.U. Vol.1//Rebirth,PS2,1,Role-Playing,Namco Bandai Games,2.031986,1.389856,3.228043,0.394830,7.226880
4,7109,.hack//G.U. Vol.2//Reminisce,PS2,1,Role-Playing,Namco Bandai Games,2.792725,2.592054,1.440483,1.493442,8.363113

In [72]:
data[data['Year'].notna()]['Year']

0        1985.0
1        2007.0
2        2012.0
3        2006.0
4        2006.0
          ...
16647    2012.0
16648    2013.0
16649    2013.0
16650    2008.0
16651    2013.0
Name: Year, Length: 16381, dtype: float64

In [73]:
data['Year']

0        1985.0
1        2007.0
2        2012.0
3        2006.0
4        2006.0
          ...
16647    2012.0
16648    2013.0
16649    2013.0
16650    2008.0
16651    2013.0
Name: Year, Length: 16652, dtype: float64

In [76]:
data['Year'] = pd.to_numeric(data[data['Year'].notna()]['Year']).astype(int)

In [78]:
data[data['Year'].notna()]['Year']

0        1985.0
1        2007.0
2        2012.0
3        2006.0
4        2006.0
          ...
16647    2012.0
16648    2013.0
16649    2013.0
16650    2008.0
16651    2013.0
Name: Year, Length: 16381, dtype: float64

In [79]:
data['Year'] = data['Year'].astype('Int64')

In [80]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16652 entries, 0 to 16651
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16652 non-null  int64
 1   Name          16652 non-null  object
 2   Platform      16652 non-null  object
 3   Year          16381 non-null  Int64
 4   Genre         16652 non-null  object
 5   Publisher     16594 non-null  object
 6   NA_Sales      16652 non-null  float64
 7   EU_Sales      16652 non-null  float64
 8   JP_Sales      16652 non-null  float64
 9   Other_Sales   16652 non-null  float64
 10  Global_Sales  16652 non-null  float64
dtypes: Int64(1), float64(5), int64(1), object(4)
memory usage: 1.4+ MB

In [81]:
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,2061,1942,NES,1985,Shooter,Capcom,4.569217,3.033887,3.439352,1.991671,12.802935
1,9137,¡Shin Chan Flipa en colores!,DS,2007,Platform,505 Games,2.076955,1.493442,3.033887,0.394830,7.034163
2,14279,.hack: Sekai no Mukou ni + Versus,PS3,2012,Action,Namco Bandai Games,1.145709,1.762339,1.493442,0.408693,4.982552
3,8359,.hack//G.U. Vol.1//Rebirth,PS2,2006,Role-Playing,Namco Bandai Games,2.031986,1.389856,3.228043,0.394830,7.226880
4,7109,.hack//G.U. Vol.2//Reminisce,PS2,2006,Role-Playing,Namco Bandai Games,2.792725,2.592054,1.440483,1.493442,8.363113

In [82]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=data)

MessageError: Error: credential propagation was unsuccessful